osx_image: xcode9.2
language: swift
podfile: Podfile

script:
  - set -o pipefail && xcodebuild -workspace Switcher.xcworkspace -scheme Switcher -sdk macosx10.13 | xcpretty
before_install:
  - pod repo update

